### ISSUE TITLE
ModificationTimestamp has wrong datatype

### ISSUE THREAD

**Issue by tentom** [AndyCW/MovesenseDotNet#11]
There is a discrepancy in the datatypes on the sensor and in the movesenseDotNet Library.
The logbook modificationTimestamp is a "uint32" on the sensor and in the library it's an "int".

This results in an error where the json deserialization will cause an exception to be thrown. 

LogEntriesMDSResult.cs
LogEntriesResult.cs

https://bitbucket.org/suunto/movesense-device-lib/src/master/MovesenseCoreLib/resources/movesense-api/mem/logbook.yaml

**Comment by AndyCW** [comment]
Thanks for reporting this. Working on a fix right now.

**Comment by tentom** [comment]
@AndyCW Do you have an estimate on when a new version will be available?

**Comment by AndyCW** [comment]
Apologies. Should be able to get this out this afternoon.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
