### ISSUE TITLE
HR issue

### ISSUE THREAD

**Issue by dikokob** [AndyCW/MovesenseDotNet#13]
Hi there,

I am trying to read HR data from the device, I am using the following piece of code:
![image](https://user-images.githubusercontent.com/6995443/57179744-46d96680-6e81-11e9-8113-fda1cd5a3e4f.png)

but I get the following error:
 Unhandled Exception:
MdsLibrary.MdsException: Com.Movesense.Mds.MdsException: Failed status: 404, reason: NOT_FOUND
  --- End of managed Com.Movesense.Mds.MdsException stack trace ---
com.movesense.mds.MdsException: Failed status: 404, reason: NOT_FOUND at com.movesense.mds.internal.operation.MdsRestOperation.onResponse(MdsRestOperation.java:81) at com.movesense.mds.internal.operation.MdsResponseOperation.protectedRun(MdsResponseOperation.java:26)
	at com.movesense.mds.internal.workqueue.QueueOperation.run(QueueOperation.java:70)
	at com.movesense.mds.internal.workqueue.WorkQueueImpl.runOperation(WorkQueueImpl.java:79)
	at com.movesense.mds.internal.workqueue.WorkQueueImpl$1.run(WorkQueueImpl.java:30)
	at java.lang.Thread.run(Thread.java:784)
 occurred

Also, will HR capability be added in the future?

**Comment by dikokob** [comment]
Found the solution.
I was using the incorrect method to subscribe to the heart rate. I was supposed to use `ApiSubscriptionAsync` instead of `ApiCallAsync`.

**Comment by dikokob** [comment]
Will **HR read** be included in the API at some point?

**Comment by wilz5363** [comment]
@dikokob , Hi, i too used `ApiSubscriptionAsync` with 
![image](https://user-images.githubusercontent.com/8830759/59186382-48472e80-8ba5-11e9-81be-47af306cb5df.png)
 but still getting 404 as below:

`06-10 17:24:37.419 I/Komposti( 2456): [SDS REQUEST] type: POST uri: suunto://MDS/EventListener contract: {"Uri": "175130000596/Meas/HR/Subscription"}
06-10 17:24:37.420 I/Komposti( 2456): Adding EventListener for path: 175130000596/Meas/HR/Subscription
06-10 17:24:37.421 D/BleManager( 2456): sendCb(10000001), 31 bytes
06-10 17:24:37.468 D/BleManager( 2456): Send complete
06-10 17:24:37.542 D/BleManager( 2456): Received data: WB_DATAMSG_CLIENT_ON_GET_RESOURCE_RESULT, type: 2, direct msg, msgLen: 8, reqId: 7424, size: 14
06-10 17:24:37.543 E/Komposti( 2456): [SDS RESPONSE] type: POST status: NOT_FOUND header: {"Status": 404, "TaskId": 30, "Reason": "NOT_FOUND", "Uri": "suunto://MDS/EventListener", "Content-Length": 0}
06-10 17:24:37.544 I/MdsOperationHandler( 2456): SDSInternalCallback with call type: 4 header: {"Status": 404, "TaskId": 30, "Reason": "NOT_FOUND", "Uri": "suunto://MDS/EventListener", "Content-Length": 0}
Unhandled Exception:`

May i know how did u resolved this?

**Comment by dikokob** [comment]
@wilz5363  Hi, there is my implementation.

![image](https://user-images.githubusercontent.com/6995443/59186854-3e590780-8b74-11e9-9ba0-53ab0afb2237.png)
![image](https://user-images.githubusercontent.com/6995443/59186883-4e70e700-8b74-11e9-80df-d3765a491f11.png)

By the way, the code isn't refactored, so I wouldn't fully advice this implementation but it works.

**Comment by wilz5363** [comment]
I think i saw the issue now. Apparently `Meas/HR` is the right path instead of `Meas/HR/Subscription`

**Comment by dikokob** [comment]
Agreed, let me know if it works.
Also @wilz5363, what are you using movesense for? Just out of interest.

**Comment by wilz5363** [comment]
With my code and the right path, it works fine now. Jz need to parse it with right format. 

Doing movesense jz for fun since it looks kinda cool

**Comment by AndyCW** [comment]
Closing this issue, as you guys have resolved it for yourselves :)
