### ISSUE TITLE
Deployment to Windows x86-64 architecture

### ISSUE THREAD

**Issue by abartolomei** [AndyCW/MovesenseDotNet#16]
I need to develop a Windows UWP application or a WPF that could use Movesense.  
Is it possible to create a C# application that works on windows with x86-64 architecture and not with ARM mobile deployments?

**Comment by AndyCW** [comment]
Unfortunately not. Movesense.NET is constrained by availability of native Mdslib native libraries published by Movesense, and those are only for Android and iOS. Please raise an issue with Movesense to request a Windows x86-64 Mdslib.
