### ISSUE TITLE
MoveSenseBindingiOS 1.38.0.2 Missing

### ISSUE THREAD

**Issue by abduelhamit** [AndyCW/MovesenseDotNet#18]
Plugin.Movesense 2.2.3.2 expects on iOS MoveSenseBindingiOS 1.38.0.**2**, but only 1.38.0.**1** is available. Thus, currently, you can't use the latest version on iOS.

**Comment by AndyCW** [comment]
Apologies, my mistake. Just pushed the package to nuget.org, so will be fine now.
