### ISSUE TITLE
Permission fails for android versions lower than Marshmallow

### ISSUE THREAD

**Issue by tentom** [AndyCW/MovesenseDotNet#4]
As run time permissions is not introduced before android Marshmallow the BasicDemo will crash. I am not sure if this is caused by the Plugin.Permission or the MovesenseDotNet library. 

As I am not familiar with Android programming I did not want to make a pull request for this issue. 

My solution was to wrap the permission check to include a version check and skip the permission check  for older versions of android. So the GetLocationPermissionAsync() now look like this:
    
    void GetLocationPermissionAsync()
    {
        //Check to see if any permission in our group is available, if one, then all are
        const string permission = Manifest.Permission.AccessCoarseLocation;
        if (Android.OS.Build.VERSION.SdkInt >= BuildVersionCodes.M) {
            if (CheckSelfPermission(permission) == (int)Permission.Granted) {
               return;
            }
            //Finally request permissions with the list of permissions and Id
            RequestPermissions(PermissionsLocation, RequestLocationId);
         }
    }

 in the mainActivity.cs file.  This might be a bad solution but it is working for me on Android Kit-Kat (4.4.2) on a Samsung galaxy s4 mini.

**Comment by AndyCW** [comment]
That's a perfectly valid solution. 
Thanks for raising though - the samples are there to demonstrate typical usage, but we leave it to you to work around platform issues such as this.
